ktor:
  application:
    modules:
      - com.ejebring.cf.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://ct.ejebring.com/"
  audience: "jwt-audience"
  realm: "ktor sample app"
